### ISSUE TITLE
Создать модель активности слушателя

### ISSUE THREAD

**Issue by HollowPrincess** [RisaMagpie/Data-Analysis#138]

**Comment by HollowPrincess** [comment]
- [x] время, потраченное на выполнение заданий проверочных и контрольных https://github.com/RisaMagpie/Data-Analysis/issues/129
- [x] время, потраченное на просмотр видео https://github.com/RisaMagpie/Data-Analysis/issues/142

- [x] количество сообщений во время прохождения темы https://github.com/RisaMagpie/Data-Analysis/issues/143

Количество времени потраченного на конспект (?) во время прохождения темы - действия можно фиксировать только при подключении специального дополнения. Такой практики не было.

Время, потраченное на чтение текстов, не было добавлено по причине того, что все действия, происходящие в логах относительно текстов являются действиями при нажатии на элементы ридера. К тому же можно просто скачать файл и тогда мы не сможем грамотно оценить время.
